---
title: Notes on Select Best Tasks for Cognitive Sub-Domain
author: Zhang, Liang
date: 2023-11-01
date-modified: last-modified
format: 
  html: 
    code-fold: true
    toc: true
execute: 
  warning: false
---

```{r}
#| label: setup

library(tidyverse)
library(lavaan)
# we need bit64 package to handle large integers
requireNamespace("bit64")
source("R/modeling.R")

projects <- targets::tar_config_yaml()
targets::tar_load(
  c(dims_origin, indices_wider_clean,
    fit_origin_bifactor, fit_origin_highorder,
    scores_origin),
  store = projects$confirm_factors$store
)
targets::tar_load(
  c(indices, durations),
  store = projects$prepare_source_data$store
)
targets::tar_load(
  reliability,
  store = projects$prepare_source_data_retest$store
)
exclude <- c(
  "CalcSpdMed.nc", "Lexic.nc", "Tone.nc",
  "NsymNCmp.w", "TOVAS.dprime", 
  "AntiSac.ies", "FPTPro.nc"
)
task_loadings <- list(
  highorder = fit_origin_highorder, 
  bifactor = fit_origin_bifactor
) |>
  map(
    ~ parameters::model_parameters(.x, standardize = TRUE) |> 
      filter(Component == "Loading") |>
      as_tibble()
  ) |> 
  bind_rows(.id = "model")
game_ver_latest <- indices |> 
  summarise(
    ver_major_latest = max(str_extract(game_version, "\\d")), 
    .by = game_id
  )
```

以下是一些基本的前提要求：

- 每个维度选择3个任务
- 保证选择出来的任务不能太类似
- 保证拟合优度达标
- 排除n-back任务
- 排除专注大师_中级（和速算师太类似）
- 排除词汇判断、声调判断（和语义判断太类似）
- 排除数感、捉虫高级版（目前被归入抑制类任务，不太典型）
- 排除连点成画、变戏法（目前被归入分配注意类任务，不太典型）

基于以上规则然后选择每个维度载荷最高的任务（基于2nd order model）：

```{r}
#| label: select-results
dim_task_sel <- task_loadings |> 
  filter(
    To != "g", 
    !From %in% exclude, 
    model == "highorder"
  ) |> 
  slice_max(Coefficient, n = 3, by = To)
dim_task_sel |> 
  separate_wider_delim(
    From, ".",
    names = c("game_name_abbr", "index_name")
  ) |> 
  left_join(data.iquizoo::game_info, by = "game_name_abbr") |> 
  left_join(game_ver_latest, by = "game_id") |> 
  left_join(durations, by = "game_id") |> 
  left_join(
    reliability |> 
      filter(
        origin == "rm_out",
        ver_major == max(ver_major), 
        .by = game_id
      ),
    by = join_by(game_id, index_name)
  ) |> 
  select(
    game_id, game_name, dim_label = To, load = Coefficient, 
    dur_min = numeric.p75, N = n, r, icc,
    ver_major_latest, ver_major
  ) |> 
  gt::gt() |> 
  gt::fmt_number(-N) |>
  gt::cols_hide(contains("ver_major")) |> 
  gt::tab_footnote(
    "Reliability measure is based on an older version.",
    gt::cells_body(
      columns = game_name,
      rows = ver_major_latest > ver_major
    )
  ) |> 
  gt::opt_footnote_marks("standard")
  # gt::opt_interactive(page_size_default = 12)
```

这些任务的拟合情况总结（整体上模型拟合优度良好）：

```{r}
#| label: show-fit-measure
#| cache: true

fit <- dim_task_sel |> 
  prepare_model(
    col_dim = "To", 
    col_task = "From", 
    hierarchical = "bifactor"
  ) |> 
  fit_cfa(indices_wider_clean, orthogonal = TRUE)
summary(fit, fit.measures = TRUE, standardized = TRUE)
```

<!-- TODO: 加入简短版本拟合情况 -->

```{r}
#| eval: false

cor_task_dim <- indices_wider_clean |> 
  pivot_longer(
    -user_id,
    names_to = "game_index",
    values_to = "score_game"
  ) |> 
  inner_join(dims_origin, by = "game_index") |> 
  inner_join(
    scores_origin |> 
      pivot_longer(
        -c(hierarchical, user_id),
        names_to = "dim_label",
        values_to = "score_latent"
      ),
    by = c("user_id", "dim_label"),
    relationship = "many-to-many"
  ) |> 
  summarise(
    r = cor(score_game, score_latent, use = "pairwise"),
    .by = c(hierarchical, game_index, dim_label)
  )
selection_1 <- cor_task_dim |> 
  filter(!game_index %in% exclude, hierarchical == "highorder") |> 
  slice_max(r, n = 3, by = dim_label)
fit_1 <- selection_1 |> 
  prepare_model(
    col_dim = "dim_label", 
    col_task = "game_index", 
    hierarchical = "bifactor"
  ) |> 
  fit_cfa(indices_wider_clean, orthogonal = TRUE)
summary(fit_1, fit.measures = TRUE, standardized = TRUE)
```
